### ISSUE TITLE
Cursor blinking when changing buffers

### ISSUE THREAD

**Issue by gegoune** [TimUntersberger/neogit#158]
I have noticed that when changing buffers with snap or fzf's `:Buffers` cursor blinks quite fast for about a second before calming down and starting to blink at its normal pace. Did you see anything like that?

**Comment by TimUntersberger** [comment]
Do you mean it blinks fast inside the NeogitStatus buffer?

**Comment by gegoune** [comment]
Ah, no, apologies for half decent issue report. It blinks on when switching between any buffers, regular buffers, not Neogit buffer.

**Comment by gegoune** [comment]
I have found out that if buffers I am switching between are for files not in git repository that is not an issue:

![ok](https://user-images.githubusercontent.com/69750637/124981956-d9b45380-e03e-11eb-8b7b-0e6ffc82a4b8.gif)

but as soon as  move those files to git repository (committed them in that example) I get the flicker:

![notok](https://user-images.githubusercontent.com/69750637/124982243-24ce6680-e03f-11eb-8828-931b85f98b60.gif)

**Comment by TimUntersberger** [comment]
Tbh, I can't really reproduce this on my machine.

Does this also occur if you switch buffers without using the plugin?

**Comment by gegoune** [comment]
It also happens with Snap, but I think not with as much flicker. Hard to tell for sure.

As to switching without fzf. I was about to respond saying that it doesn't happen, but it does. It's harder to see in my minimalistic test repo but in my dot files repository it is noticeable when using any of those:

- `:b#`
-  tpope/vim-unimpaired's `[b` and `]b` or `[f` and `]f`

But I must say that it does not feel as bad using above methods.
Can you think of a way to make it more palpable, easier to debug?

**Comment by gegoune** [comment]
I have found the culprit:

```
luatree  User
    NeogitStatusRefreshed
              NvimTreeRefresh
```

This autocommand to refresh ivim-tree's git status. Seems to be firing on but enter too?

**Comment by TimUntersberger** [comment]
> I have found the culprit:

Just to make sure: If you remove this line you no longer encounter the flicker no matter what you do?

**Comment by gegoune** [comment]
That is correct.

**Comment by TimUntersberger** [comment]
Well `NeogitStatusRefreshed` gets emitted whenever we refresh the status and this happens frequently.

Maybe the culprit is more the `NvimTreeRefresh` command?

**Comment by gegoune** [comment]
It definitely might be the case. @kyazdani42, can you think of a reason why  `NvimTreeRefresh` would cause cursor flickering?

@TimUntersberger , do you think emitting `NeogitStatusRefreshed` would benefit from small debounce?

**Comment by kyazdani42** [comment]
you can remove the autocmd, i've fixed the neogit integration in nvim-tree.

**Comment by gegoune** [comment]
@kyazdani42 autocmd was there to update nvim-tree's it status after Neogit's git operations. I have just pulled latest changes and without that autocmd I am not getting up to date git statuses in nvim-tree after, let's say, staging file with Neogit. I think your fix was for some other use case maybe?

**Comment by kyazdani42** [comment]
it seems related to the `vim.fn.system` and `vim.fn.systemlist` calls somehow, i'm not sure why though

**Comment by TimUntersberger** [comment]
So I guess I can close this?

**Comment by gegoune** [comment]
I have just tried to remove neogit out of equation and it indeed not flicker any more. I am not sure where the problem lies, whether it is neogit the firing event too often (too many times at once) or nvim-tree doing something when `NvimTreeRefresh` gets called.

**Comment by kyazdani42** [comment]
should be fixed in latest master in nvim-tree. Was my fault, i was redrawing the tree many times and the cursor back and forth made the ui flicker...

**Comment by TimUntersberger** [comment]
@kyazdani42 good job!

**Comment by gegoune** [comment]
@TimUntersberger I am really sorry to dig out that old issue, but I am still seeing flicker when changing buffers, which goes away if Neogit is uninstalled. I love using your plugin and would really like to get rid of that flicker (I have disabled blinking cursor in my terminal now, but when switching buffers it blinks few times).

I am seeing that autocmd which gets executed when entering buffers:

```
Neogit  BufEnter
    *         call <SID>refresh(expand('<afile>'))
```

Perhaps that's the issue? Is it necessary? Should Neogit only refresh its status when `:Neogit` is executed? I am not sure how it works internally though so please forgive me if I am talking nonsense here.

**Comment by gegoune** [comment]
I can completely get rid of the flicker with this change

```diff
diff --git a/plugin/neogit.vim b/plugin/neogit.vim
index 78d2394..903b0cc 100644
--- a/plugin/neogit.vim
+++ b/plugin/neogit.vim
@@ -16,8 +16,6 @@ endfunction

 augroup Neogit
   au!
-  au BufWritePost,BufEnter,FocusGained,ShellCmdPost,VimResume * call <SID>refresh(expand('<afile>'))
-  au DirChanged * lua vim.defer_fn(function() require 'neogit.status'.dispatch_reset() end, 0)
   au ColorScheme * lua require'neogit.lib.hl'.setup()
 augroup END
```

Which led me to

```lua
diff --git a/plugin/neogit.vim b/plugin/neogit.vim
index 78d2394..ea0723a 100644
--- a/plugin/neogit.vim
+++ b/plugin/neogit.vim
@@ -9,8 +9,10 @@ endif

 function! s:refresh(file)
   if match(bufname(), "^\\(Neogit.*\\|.git/COMMIT_EDITMSG\\)$") == 0
+    echom 'skipping'
     return
   endif
+    echom 'refreshing'
   call luaeval('(function() require "neogit.status".refresh_viml_compat(_A) end)()', a:file)
 endfunction
```

and it seems like I am getting `refreshing` printed out on every buffer switch pointing to conditional not working properly.

From `help match()`:

> 		A match at the first character or |List| item returns zero.
>		If there is no match -1 is returned.

So I am wondering whether this conditional should check for `-1`. If so,

```diff
diff --git a/plugin/neogit.vim b/plugin/neogit.vim
index 78d2394..afb944c 100644
--- a/plugin/neogit.vim
+++ b/plugin/neogit.vim
@@ -8,7 +8,7 @@ if !luaeval("require 'neogit.bootstrap'")
 endif

 function! s:refresh(file)
-  if match(bufname(), "^\\(Neogit.*\\|.git/COMMIT_EDITMSG\\)$") == 0
+  if match(bufname(), "^\\(Neogit.*\\|.git/COMMIT_EDITMSG\\)$") == -1
     return
   endif
   call luaeval('(function() require "neogit.status".refresh_viml_compat(_A) end)()', a:file)
```

removes flicker when switching buffers within PWD (without triggering `DirChanged` (I am using project.nvim to change PWD to git's root); flicker still exists when switching buffer from different repos.

And I am still trying to figure out why is Neogit refreshing on each buffer change and not only when its windows are opened.

Is there anything else I could check or do to help resolve that?

**Comment by TimUntersberger** [comment]
We have to refresh as often as possible to keep our state in sync with git. Have you tried just removing the `BufEnter` condition?

**Comment by kyazdani42** [comment]
hi ! why not loading git when needed ? a bufenter event will not change anything in git.
I do only update git in nvim tree just when needed and it works just well.
If you could, maybe add different autocmd names so we can subscribe to the one we actually need?

**Comment by gegoune** [comment]
This is exactly what I was thinking. Why not just read fit status on Neogit command?  I really would might waiting half a second more for window to render. 

Please don't get me wrong here, not trying to argue, just want to understand reasoning here.

**Comment by TimUntersberger** [comment]
>  I really would might waiting half a second more for window to render.

Such a load time is unacceptable.

Have you tried the autocommands without `BufEnter`?

> just want to understand reasoning here.

Right now you can leave Neogit open in a split and continue editing your files while seeing live updates to your git status. Some people want to use Neogit like this so I won't remove the support for this.

**Comment by gegoune** [comment]
> Have you tried the autocommands without `BufEnter`?

Yes, I believe I tried when figuring out what's going on. It worked just fine for my use case. 

> Right now you can leave Neogit open in a split and continue editing your files while seeing live updates to your git status. Some people want to use Neogit like this so I won't remove the support for this.

Ah, and this is use case I did not think about. It's very fair. I did not think about it because I always open Neogit in new tab only. 
Perhaps update frequency could be configurable? Keep defaults as they are now but allow users to change it. 

Sometime I have long sessions when I don't use Neogit at all and those updates are unnecessary for me. 

I would very happily use that option to change it to 'on Neogit buffer/window open'. 

What do you think about that?

Another, probably less desirable, solution would be to keep updating Neogit as it is done now but avoid redrawing (I believe this is what is causing the flicker but am not in front of computer to confirm this) unless its window is actually displayed.

**Comment by gegoune** [comment]
This works perfectly for my use case:

```diff
diff --git a/plugin/neogit.vim b/plugin/neogit.vim
index 78d2394..2104c44 100644
--- a/plugin/neogit.vim
+++ b/plugin/neogit.vim
@@ -16,8 +16,7 @@ endfunction

 augroup Neogit
   au!
-  au BufWritePost,BufEnter,FocusGained,ShellCmdPost,VimResume * call <SID>refresh(expand('<afile>'))
-  au DirChanged * lua vim.defer_fn(function() require 'neogit.status'.dispatch_reset() end, 0)
+  au BufEnter Neogit call <SID>refresh(expand('<afile>'))
   au ColorScheme * lua require'neogit.lib.hl'.setup()
 augroup END
```

So if there was an option to set it up like that I would definitely be doing this and be happy.

**Comment by TimUntersberger** [comment]
I guess adding an `after/plugin/neogit.vim` file, where you remove the autocommands is an easy solution for now.

`after/plugin/neogit.vim`
```vim
autocmd! Neogit
au BufEnter NeogitStatus call luaeval('(function() require "neogit.status".refresh_viml_compat(_A) end)()', a:file)
```
