### ISSUE TITLE
`disable_insert_on_commit` is broken

### ISSUE THREAD

**Issue by kuntau** [TimUntersberger/neogit#426]
### Description

`disable_insert_on_commit=false` no longer work.

Commit window no longer open in insert mode.

### Neovim version

NVIM v0.9.0-dev-cb9d68fe
Build type: Release
LuaJIT 2.1.0-beta3 

### Operating system and version

MacOS 10.15.7

### Steps to reproduce

1. Open neogit
2. Commit file

### Expected behavior

Commit window open in `insert` mode

### Actual behavior

Commit window open in `normal` mode

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by Fabian-programmer** [comment]
When I open a new nvim instance and execute :Neogit, I'm also directly in 'insert' mode. This happens just once. Maybe it is related?

**Comment by ten3roberts** [comment]
Does https://github.com/TimUntersberger/neogit/tree/fix-%23401 do anything different for you?

**Comment by Fabian-programmer** [comment]
`disable_insert_on_commit=false` works for me when I write it into my config.

I still starts neogit in insert mode.

**Comment by ten3roberts** [comment]
Just to clarify, are you in insert mode when doing `cc` and the commit buffer opens, or are you placed in insert mode in the neogit status buffer?

**Comment by Fabian-programmer** [comment]
![2023-01-08_13h47_26](https://user-images.githubusercontent.com/65787013/211196868-6b2a9044-878d-4c6b-b58b-43b9372966bf.gif)

and my config

```
return {
  "TimUntersberger/neogit",
  -- dir = "~/neogit",
  cmd = "Neogit",
  lazy = false,
  config = {
    disable_commit_confirmation = true,
    disable_insert_on_commit = false,
    signs = {
      -- { CLOSED, OPENED }
      section = { "", "" },
      item = { "", "" },
      hunk = { "", "" },
    },
    integrations = { diffview = true },
  },
  keys = {
    { "<leader>gg", "<cmd>Neogit<cr>", desc = "Neogit" },
    { "<leader>gl", function()
      require("neogit.popups.log").create()
      vim.cmd('normal l')
      vim.cmd(':wincmd p| wincmd T')
    end, desc = "Log current" },
    { "<leader>gL", function()
      require("neogit.popups.log").create()
      vim.cmd('normal b')
      vim.cmd(':wincmd p| wincmd T')
    end, desc = "Log" },
  },
}
```

**Comment by ten3roberts** [comment]
That is even more strange.

If you comment out `vim.cmd(":startinsert")` in https://github.com/TimUntersberger/neogit/blob/458012d3c6853525d169e5dd9aa153b2ca157d80/lua/neogit/buffers/commit_editor/init.lua#L77

Does it still happen?

If so, there may be some other autocmd in another plugin or config file

**Comment by Fabian-programmer** [comment]
When i remove that line, the commit window never starts in isnert mode.

The strange thing is, the start of neogit in insert mode, only happens once. 
I'd assume if there is an autocommand, it would happen all the time.

**Comment by Fabian-programmer** [comment]
I think i have found the guilty line in my config:

`vim.api.nvim_command('autocmd TermOpen,TermEnter * startinsert')`

I'm just wondering why it happens.

**Comment by ten3roberts** [comment]
Right, the starting of insert mode in the commit window is expected.

But if it still enters insert mode for the statusbuffer without that line is could be an autocmd like BufEntered.

Was just about to comment that 

[vim.api.nvim_command('autocmd TermOpen,TermEnter * startinsert')](https://github.com/Fabian-programmer/nvim/blob/7475fd937a7f2d27e477f742fabd9b28367a5b4a/lua/config/commands.lua#L1)

It could be that as Neogit opens the statusbuffer, the console window for git commands (the popup when a command fails) opens. It is a terminal buffer, but it is hidden. It could be the the autocmd triggers on that, and since it is hidden, the "current" buffer is the neogit window.

Which also explains the "only happens once" as the console window is kept in the background, and just reused

**Comment by Fabian-programmer** [comment]
Thank you!

Fixes it for me
`vim.api.nvim_command('autocmd TermOpen,TermEnter term://* startinsert')`

For me both "bugs" are fixed.

**Comment by ten3roberts** [comment]
@kuntau does it work for you? If so, I'll close this issue.

The problem was that the `initialize` method when opening the commit buffer was not called in the commit buffer as current buffer

**Comment by kuntau** [comment]
> @kuntau does it work for you? If so, I'll close this issue.
> 
> The problem was that the `initialize` method when opening the commit buffer was not called in the commit buffer as current buffer

Sorry for late reply, I got away for a while.

Do I need to make any change to my config? I just downloaded the new update but still have the same behavior like before.

**Comment by kuntau** [comment]
Changed my term autocmd to `vim.api.nvim_command('autocmd TermOpen,TermEnter term://* startinsert')`

Main neogit window no longer open in insert mode, but commit window `cc` still don't auto open in `insert` mode

**Comment by ten3roberts** [comment]
Wouldn't minimal config in that case be 
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup {
              disable_insert_on_commit = false,
          }
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

This will cause the commit message window to open in `insert` mode
```lua
require("neogit").setup {
    disable_insert_on_commit = false,
}
````

whereas this will cause it to open in `normal` mode
```lua
require("neogit").setup {}
````

**Comment by kuntau** [comment]
After some hours of hair pulling debugging sessions, I found out the culprit is [windows.nvim](https://github.com/anuvyklack/windows.nvim) 🤔🤯🤨😵🙃🤦🤦🙄

Thank you for your time

**Comment by ten3roberts** [comment]
I've also had trouble with that plugin, like Aerial window not resizing, and weird insert modes you can't escape, like being stuck inside the terminal in insert mode.

Great that it all worked out for you.

**Comment by kuntau** [comment]
I just found out if you disabled the animation extension there's no weird bug anymore. Neogit insert mode in commit works just fine. 


It's a shame though because I really like the animation.
