### ISSUE TITLE
Plenary error when starting nvim

### ISSUE THREAD

**Issue by wrightjjw** [TimUntersberger/neogit#467]
### Description

When opening nvim on Windows I get the following error message. I'm not sure if this is an issue in plenary or neogit, but removing neogit initialization fixes the problem (I'm just using the default `require('neogit').setup{}`). Looks like it's probably a Windows filepath problem though. I'm able to create files and directories with neotree which also relies on plenary, making me think this is a neogit problem.

```
Error detected while processing C:\Users\Joshua\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:497: We couldn't mkdir: C:\Users\Joshua\AppData\Local\nvim-data/neogit/C:
stack traceback:
        [C]: in function 'error'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:497: in function 'mkdir'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:630: in function 'touch'
        ...a\site\pack\packer\start\neogit/lua/neogit/lib/state.lua:51: in function 'read'
        ...a\site\pack\packer\start\neogit/lua/neogit/lib/state.lua:33: in function 'setup'
        ...l\nvim-data\site\pack\packer\start\neogit/lua/neogit.lua:61: in function 'setup'
        ...l\nvim-data\site\pack\packer\start\neogit/lua/neogit.lua:76: in main chunk
        [C]: in function 'require'
        C:\Users\Joshua\AppData\Local\nvim/lua/plugins.lua:166: in main chunk
        [C]: in function 'require'
        C:\Users\Joshua\AppData\Local\nvim\init.lua:2: in main chunk
```

### Neovim version

NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 11

### Steps to reproduce

run nvim

### Expected behavior

nvim starts normally

### Actual behavior

the above error

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by CKolkey** [comment]
Could you let me know if this fixes it? I don't have a windows machine/vm to test with: https://github.com/TimUntersberger/neogit/pull/468

**Comment by wrightjjw** [comment]
@CKolkey Thanks for the quick response! There's still an error but it looks slightly different now:
```
Error detected while processing C:\Users\Joshua\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: Could not create
file: C:\Users\Joshua\C:/Users/Joshua/AppData/Local/nvim-data/neogit/ca42a1594bf748ef425d7847cc20fb80
stack traceback:
        [C]: in function 'error'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: in function 'touch'
        ...a\site\pack\packer\start\neogit/lua/neogit/lib/state.lua:52: in function 'read'
        ...a\site\pack\packer\start\neogit/lua/neogit/lib/state.lua:34: in function 'setup'
        ...l\nvim-data\site\pack\packer\start\neogit/lua/neogit.lua:61: in function 'setup'
        ...l\nvim-data\site\pack\packer\start\neogit/lua/neogit.lua:76: in main chunk
        [C]: in function 'require'
        C:\Users\Joshua\AppData\Local\nvim/lua/plugins.lua:168: in main chunk
        [C]: in function 'require'
        C:\Users\Joshua\AppData\Local\nvim\init.lua:2: in main chunk
```

**Comment by CKolkey** [comment]
Yea, no worries. I updated the branch, could you give that a spin and let me know?

**Comment by wrightjjw** [comment]
Still not working I'm afraid.
```
Error detected while processing C:\Users\Joshua\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: Could not create
file: C:\Users\Joshua\C:/Users/Joshua/AppData/Local/nvim-data/neogit/ca42a1594bf748ef425d7847cc20fb80
stack traceback:
        [C]: in function 'error'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: in function 'touch'
        ...a\site\pack\packer\start\neogit/lua/neogit/lib/state.lua:52: in function 'read'
        ...a\site\pack\packer\start\neogit/lua/neogit/lib/state.lua:34: in function 'setup'
        ...l\nvim-data\site\pack\packer\start\neogit/lua/neogit.lua:61: in function 'setup'
        ...l\nvim-data\site\pack\packer\start\neogit/lua/neogit.lua:76: in main chunk
        [C]: in function 'require'
        C:\Users\Joshua\AppData\Local\nvim/lua/plugins.lua:163: in main chunk
        [C]: in function 'require'
        C:\Users\Joshua\AppData\Local\nvim\init.lua:2: in main chunk
```

I did a bit of testing on my own with this script:
```lua
local path = require('plenary.path')

local base = vim.fn.stdpath("state") .. "/neogit/"
local modified = vim.fs.normalize(base .. "file")
local filepath = path:new(modified)

print(filepath)

filepath:touch() { parents = true }
```

Output:
```
C:/Users/Joshua/AppData/Local/nvim-data/neogit/file
Error detected while processing C:\Users\Joshua\AppData\Local\nvim\test.lua:
E5113: Error while calling lua chunk: ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: Could not create file: C:\Users\Joshua\AppData\Local\nvim\C:/Users/Joshua/AppData/Local/nvim-data/neogit/file
stack traceback:
        [C]: in function 'error'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: in function 'touch'
        C:\Users\Joshua\AppData\Local\nvim\test.lua:9: in main chunk
```

I'm starting to think this might be a bug in plenary, since the value of `filepath` looks valid but `touch()` adds `C:\Users\Joshua\Appdata\Local\nvim` at the start of the path...

**Comment by wrightjjw** [comment]
Normalize is definitely a factor.
```lua
local path = require('plenary.path')

local base = vim.fn.stdpath("state") .. "/neogit/"
local modified = base .. "file"
local filepath = path:new(modified)

print(filepath)

filepath:touch() { parents = true }
```

```
C:\Users\Joshua\AppData\Local\nvim-data/neogit/file
Error detected while processing C:\Users\Joshua\AppData\Local\nvim\test.lua:
E5113: Error while calling lua chunk: ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: Could not create file: C:\Users\Joshua\AppData\Local\nvim-data/neogit/file
stack traceback:
        [C]: in function 'error'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:635: in function 'touch'
        C:\Users\Joshua\AppData\Local\nvim\test.lua:9: in main chunk
```

I don't know much about Lua, I'm just trying things related to the edits you made 😁

**Comment by CKolkey** [comment]
Hmm.. odd. Ok. I'll spin up a VM tomorrow and see if I can reproduce/fix this. Maybe its related to the path separators? I thought windows handled either forward or back-slashes, but maybe Im mistaken.

**Comment by CKolkey** [comment]
Small thing with the snippet you posted: I think the last line should be `filepath:touch({ parents = true })` if you add parens. 

I I tried to use the correct path separators, lemme know if thats better.

**Comment by wrightjjw** [comment]
#470 seems to fix the issue!
