### ISSUE TITLE
Pressing tab on a line that cannot be expanded in the status buffer errors

### ISSUE THREAD

**Issue by akinsho** [TimUntersberger/neogit#76]
![image](https://user-images.githubusercontent.com/22454918/112474699-dafb9200-8d67-11eb-8820-96f71a532ae6.png)
When using tab to toggle folds in the neogit status buffer, if a user presses tab over a line that does not support unfolding it shows the error above.

To reproduce this try pressing tab on the line of a particular stash or a section in the unmerged block.

**Comment by TimUntersberger** [comment]
This is not happening for 🤔.

I tried with both a stash item and unmerged item.

**Comment by akinsho** [comment]
@TimUntersberger sorry I just had another go and was able to narrow it down further, it seems to only happen when signs are enabled

**Comment by TimUntersberger** [comment]
Should be fixed in the latest version

**Comment by akinsho** [comment]
Yep just tested it and that's resolved, thanks 👍🏿 will close this now

**Comment by akinsho** [comment]
Actually @TimUntersberger I spoke to soon it doesn't happen on `Stashes` anymore but it still happens in the `Unmerged into <branch>` section

**Comment by RianFuro** [comment]
@akinsho should be fixed with a52ddc

**Comment by akinsho** [comment]
Yep that fixed it 👍🏿
